version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
          keys:
            - pbacp-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: pbacp-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - codecov/upload
      - run:
          name: Run Build
          command: npm run build

workflows:
  version: 2

  test:
    jobs:
      - test
